### ISSUE TITLE
Wrong number of pomodori, when there is no long break

### ISSUE THREAD

**Issue by hryniuk** [okraits/omodoro#10] opened 2016-09-04 00:15 UTC
If I see correctly, `cnt_pomodori` is initialized with default value of `num_pomodori` and it's changed to correct value only when long break is over. So, when **omodoro** is called with `1-1-1-1` there are still four pomodori in the cycle.

**Comment by okraits** [comment] 2018-01-09 21:01
Yes, you are right. The issue is fixed in https://github.com/okraits/omodoro/commit/ba8867801cf42bc50d9615a9a5cc39299fcb6d88.

Thank you very much for reporting the issue and sorry for responding to this with such a huge delay.

**Closed by okraits** 2018-01-09 21:01 UTC

**Comment by hryniuk** [comment] 2018-01-09 21:27
Well done :).

**Comment by okraits** [comment] 2018-01-10 06:49
Thanks :-) Well, it was an easy and obvious one :-)
